# Generated by Django 3.2.22 on 2023-10-29 04:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESGProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('company_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='project_logos/')),
                ('start_date', models.DateField()),
                ('owner_name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('task_name', models.CharField(max_length=200)),
                ('schedule', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='esg_projects.esgproject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
